# Generated by Django 5.0.1 on 2024-06-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexusapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(default='', max_length=20)),
                ('Lname', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Datas',
        ),
    ]
